### ISSUE TITLE
Noteworthy labels for Polkadot

### ISSUE THREAD

**Issue by ggwpez** [paritytech/labels#24]
For example the MR https://github.com/paritytech/polkadot/pull/6928 modifies `XCM`. I therefore put `B1-note_worthy` and `T6-XCM`, but that does not work.  
Neither does `B1-note_worthy`+`T6-XCM`+`T1-runtime`. The CI *requires* me to remove the `T6-XCM` label, which is definitely needed for downstream parachain teams. Can we allow multiple `T*` labels?  
I remember there was a recent MR about a similar situation, but this time i have a more concrete approach. IMHO the these `T*` labels should be treated as Tags; therefore allowing multiple but requiring at least one. WDYT?

**Comment by the-right-joyce** [comment]
hi Oliver,
unfortunately we can't. We had it like this that even when mentioning `B1-note_worthy` we still could add additional `T*` labels, but this broke the release notes and as we want to move to a mono-repo we thought as a quick fix set the rules that it only allows one `T*`-label when it should be mentioned in the releases.
What we can do is going back to what we had in the very beginning: we put the release-related labels (runtime, node, API) as an extra category (`X*`) so that you can still add as many `T*` labels as you want. Is that fine?

Once we start working on the mono-repo we should start from scratch and have proper requirements for what we need labels first (CI tooling and bots, release analysis of Hector and his team, contribution on substrate and polkadot, LTS branch, etc.) and with this as a base then set rules for them.

**Comment by ggwpez** [comment]
Okay thanks @the-right-joyce. I think the additional `X` labels are a good idea.  

Maybe it is worth writing a short forum post with that to see if other devs have suggestions/objections.
